### ISSUE TITLE
Add button for installing

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/expense-manager-demo#111]
For a better UX, add a button or other way in the UI to initiate the install https://developers.google.com/web/updates/2018/06/a2hs-updates

The automatic prompt is going away in Chrome 68

**Comment by limonte** [comment]
There's [mini-infobar](https://developers.google.com/web/updates/2018/06/a2hs-updates#the_mini-infobar) which is a Chrome UI component and is not controllable by the site. It will be always shown if an app meets all PWA requirements despite anything we add or remove to the codebase

![image](https://user-images.githubusercontent.com/6059356/49003975-df99e680-f16b-11e8-8e17-deb6ecbd0220.png)
