### ISSUE TITLE
Merchant combo : vaadin-overlay-behavior.html:105 Uncaught ReferenceError: unwrap is not defined

### ISSUE THREAD

**Issue by komasoftware** [vaadin/expense-manager-demo#19]
The combo for the merchant gives an error when running local .. maybe I amd doing something wrong. Any idea ?

Local I see this (and the combox box does not work) : 

![selection_432](https://cloud.githubusercontent.com/assets/482152/14942447/ac94ddae-0fbd-11e6-89a7-693f59672669.jpg)

The Live demo shows :

![selection_434](https://cloud.githubusercontent.com/assets/482152/14942456/e1c09cd4-0fbd-11e6-8ad7-e8b591933bdd.jpg)

In the console I have the error 
`vaadin-overlay-behavior.html:105 Uncaught ReferenceError: unwrap is not defined`

![selection_431](https://cloud.githubusercontent.com/assets/482152/14941648/716446ee-0fa3-11e6-8cfa-d9fbbe9fd512.jpg)

![selection_435](https://cloud.githubusercontent.com/assets/482152/14942465/169b818a-0fbe-11e6-84b4-19a2f352f20e.jpg)

When I put a breakpoint in the _setPosition function on the LIve demo, the function is not being called... ?

**Comment by marcushellberg** [comment]
Hi, thanks for reporting. I suspect that you may have a newer pre-release version of combo-box. Can you check your bower listing and report what version you are on? Also try setting the version to 1.0.0.rc1 explicitly in bower.js and see if that fixes it.

**Comment by marcushellberg** [comment]
I can see the same problem on my end. Filed an issue on vaadin-combo-box https://github.com/vaadin/vaadin-combo-box/issues/233

**Comment by komasoftware** [comment]
It works now with dependency : 

`"vaadin-combo-box": "^1.0.0-beta2"`

**Comment by marcushellberg** [comment]
This should now be fixed with the rc3 version of combo-box.
