### ISSUE TITLE
'To be reimbursed' label randomly shown

### ISSUE THREAD

**Issue by manolo** [vaadin/expense-manager-demo#35]
- In desktop big screen, the 'To be reimbursed' label is sometimes hidden, sometimes shown but in the background of the title bar.

**Comment by marcushellberg** [comment]
Cannot reproduce. Try shift-refreshing to make sure you have all the newest content. If you keep seeing this, please add a screen short to help me debug.

**Comment by manolo** [comment]
Does not happen anymore after some colour changes.
