### ISSUE TITLE
Add / Edit expense dialog position wrong on Firefox

### ISSUE THREAD

**Issue by Wnt** [vaadin/expense-manager-demo#38]
On firefox the Add / Edit expense dialog opens in to the lower left corner instead of in the middle of the screen
![screenshot from 2016-05-20 15-25-29](https://cloud.githubusercontent.com/assets/886091/15427668/5ac4cf84-1e9f-11e6-9ff5-96822f5e0f18.png)
![screenshot from 2016-05-20 15-25-14](https://cloud.githubusercontent.com/assets/886091/15427669/5ac541e4-1e9f-11e6-9c08-921badcf4d3a.png)

**Comment by marcushellberg** [comment]
Fixed
