### ISSUE TITLE
"Upload new receipt" option goes behind the scrollbar in desktop

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/expense-manager-demo#4]
Displaying the list option breaks down as in the attached screenshot on desktop. On mobile, the three-dot-menu icon to open the list is completely missing (i.e. you cannot replace the receipt on mobile).
![screen shot 2015-12-11 at 10 24 19](https://cloud.githubusercontent.com/assets/13781525/11739258/cdd4f6ba-9ff2-11e5-90ed-101b5e4da876.png)

**Comment by marcushellberg** [comment]
This is a polymer bug that I've reported a long time ago. I haven't been able to figure out a workaround for it yet.

**Comment by marcushellberg** [comment]
As a workaround, I changed the vertical ellipsis to an upload icon that just directly triggers the upload to avoid dealing with the menu.
