### ISSUE TITLE
back button bug with new expense on mobile.

### ISSUE THREAD

**Issue by joeblew99** [vaadin/expense-manager-demo#45]
Must click back button twice on mobile, if you previously clicked cancel.
Context:
- Android latest stock nexus 6.

Steps to Repro:

click the new button to make a new expense
- click cancel and it will close the dialog
  click the new button again
- click the mobile "back" button. Nothing will happen
- click the mobile "back" button. It will close.

**Comment by marcushellberg** [comment]
Thanks. I'll take a look at this.

**Comment by marcushellberg** [comment]
Can you check if you are able to reproduce it on this instance? https://vaadin.github.io/expense-manager-demo/

I was not able to reproduce with a Nexus 6P

**Comment by joeblew99** [comment]
i could not reproduce this time either, except at the start and then after 15 goes i gave up.

the speed gets faster in terms of opening the form. i guess the hotspot vm doing its thing.

so maybe its a heuristic of the vm hotspot 

then i refreshed and tried again. after 10 attempts i hit the bug on my nexus 6.
i know i hit it because the mobile makes a sound when you hit the back button.
its a weird timing thing. 

i know this is picky. most people would not get fussed about it.

**Comment by marcushellberg** [comment]
Ok, thanks for checking. I'll keep my eye out for this to see if I can reproduce. Always fun to figure out these "sometimes" bugs :)

**Comment by joeblew99** [comment]
One last really picky question. Last one I promise.
I ask this because I am building a real time collaborative editor and
thinking about using polymer and pouch.

If I take if offline, edit an item, when I go online will it sync with
couchdb ?
It seems to be following the first one in wins too

**Comment by marcushellberg** [comment]
That's the default if you don't handle it yourself. You can also decide to handle the conflict yourself and have full control over how to handle it: https://pouchdb.com/guides/conflicts.html

**Comment by joeblew99** [comment]
Cheers
