### ISSUE TITLE
CORS data access blocked with URL provided to allow access

### ISSUE THREAD

**Issue by jparish3** [vaadin/expense-manager-demo#46]
Using Chrome extension for Allow-Control-Allow-Origin: 

From Vaadin demo Site:
 XMLHttpRequest cannot load https://em2db.demo.vaadin.com/db_0e7ab06211/. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://wc.demo.vaadin.com' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

From polymer serve:
XMLHttpRequest cannot load https://em2db.demo.vaadin.com/db_9e5c96a3b0/. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by marcushellberg** [comment]
Are you able to use it without the plugin? I am able to access the demo just fine on my end without any plugins.

**Comment by jparish3** [comment]
By plug-in do you mean the chrome extension? After my post, I returned to
both the local & Vaadin site demos and data had been populated. I am now
able to turn off the extension and the data appears to be working (have not
written new records). The error messages below remain with pouchDB follow
on to 404. I have not used pouchDB before, so maybe the initial CORS block
was related, but only a temporary block(?). As an aside what is the
difference between the Vaadin PuchDB element and the polymer Element (
https://elements.polymer-project.org/elements/app-pouchdb)?
Remaining Console Messages after initial data load:
XMLHttpRequest cannot load https://em2db.demo.vaadin.com/db_9e5c96a3b0/. A
wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header
when the credentials flag is true. Origin 'http://localhost:8080' is
therefore not allowed access. The credentials mode of an XMLHttpRequest is
controlled by the withCredentials attribute.
24overview-page.html:256 update
https://em2db.demo.vaadin.com/db_9e5c96a3b0/_local/twrQMLUlkFCnJo8zB5g.wg%3D%3D?
Failed to load resource: the server responded with a status of 404 (Object
Not Found)
pouchdb.js:927
The above 404 is totally normal. PouchDB is just checking if a remote
checkpoint exists.
26overview-page.html:256 update
https://em2db.demo.vaadin.com/db_9e5c96a3b0/_local/8VqeZV86o4sk_FlVAV.lFA%3D%3D?
Failed to load resource: the server responded with a status of 404 (Object
Not Found)
https://em2db.demo.vaadin.com/db_9e5c96a3b0/_local/twrQMLUlkFCnJo8zB5g.wg%3D%3D?
Failed to load resource: the server responded with a status of 404 (Object
Not Found)
pouchdb.js:927
The above 404 is totally normal. PouchDB is just checking if a remote
checkpoint exists.
https://em2db.demo.vaadin.com/db_9e5c96a3b0/_local/8VqeZV86o4sk_FlVAV.lFA%3D%3D?
Failed to load resource: the server responded with a status of 404 (Object
Not Found)
pouchdb.js:927 The above 404 is totally normal. PouchDB is just checking if
a remote checkpoint exists.

**Comment by marcushellberg** [comment]
The main difference between the two pouchdb implementations is that vaadin-pouchdb also has a browser local db that is kept in sync. 

I'm still not seeing any CORS issues on my end. Not sure what is causing you to see them.
