### ISSUE TITLE
Readme outdated / incomplete

### ISSUE THREAD

**Issue by Wnt** [vaadin/expense-manager-demo#47]
It is not possible to get a local development version running using the README.md instructions without previous knowledge about Polymer, PouchDB, Vaadin Elements etc.
e.g. the mentioned `<pouch-db>` element is missing from `overview-page.html` and simly running `polymer build` fails with
`Error: ENOENT: no such file or directory, open '/home/jonni/Downloads/expense-manager-demo/bower_components/polymer/polymer.html'`

**Comment by marcushellberg** [comment]
Thanks, the readme was missing the step to install bower dependencies. Should be fixed now.
