### ISSUE TITLE
Online Demo no longer working?

### ISSUE THREAD

**Issue by ygagnon** [vaadin/expense-manager-demo#48]
I was very excited to come across this web app, and was eager to experiment with it.  However, it appears that the online demo version isn't working. It loads up fine, but it doesn't actually save any of the data that's entered.  I've tried various different devices and browsers, but all of them have the same behavior.  And my developer console is displaying numerous errors that I suspect might be related to couchDB.  

Are there any special requirements in order for this application to work .. like the enabling of a flag in the browser settings or something similar?  And are there any special hosting or server configuration requirements? 

Thanks,
- Yvan

**Comment by marcushellberg** [comment]
Indeed, there seems to be something wrong with our database server. Thanks for letting me know. It should work fine if you want to try it locally against your own couchdb, just change the address in the code. 

I'll update this issue when I figure out what's going on with our DB server.

**Comment by ygagnon** [comment]
Ah .. I see you got the database connectivity restored.  Thanks!  This really is a slick application.  

So if I wanted to set up this up on a remote linux-based hosting environment, would there be any special server-side requirements?  I ask because I'm assuming that CouchDB isn't typically enabled or available on shared hosting environments.  Is that correct?  

Also -- is there a reason why it isn't possible to delete entries that have an receipt image attached?  Was that by design?  And are those images actually being physically stored somewhere on the server?  Or are you just base64 encoding them and storing them in the database?

**Comment by marcushellberg** [comment]
We got the DB issue fixed. There seems to be something else going on too as it's not connecting other clients with the same database id in the URL to the same database. Need to figure out what's going on. 

Images are stored in the same CouchDB as the rest of the data. There should be no reason why you couldn't remove entries with images, it has worked before. Need to look into that too. 

You probably won't find CouchDB on shared hosting environments. You could look into something like https://cloudant.com/ if you don't want to host it yourself.
