### ISSUE TITLE
Additional filters missing on mobile

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/expense-manager-demo#5]
"Min($)" and "Max($)" and "Status" filters are not accessible on mobile. Even if other filters except "Merchant" are hidden on purpose, there should be less padding above and more padding below the "Merchant" input on mobile. Screenshot with desktop and mobile side by side:
![screen shot 2015-12-11 at 10 30 56](https://cloud.githubusercontent.com/assets/13781525/11739274/ecd68efc-9ff2-11e5-9299-b2f0ac8c61d9.png)

**Comment by tuomasnironen** [comment]
Well. Apparently the filters ARE there but... (iPhone horizontally) :D Is this caused by media query pixel limits regarding responsiveness? Maybe just tweak those.

It might be actually nice to be able to toggle all of the filters visible/hidden to see more of the grid. However, no visuals for that available (yet). 

![screen shot 2015-12-11 at 12 43 03](https://cloud.githubusercontent.com/assets/13781525/11741940/d2a87470-a004-11e5-9ce2-94b24c195255.png)

**Comment by marcushellberg** [comment]
I limited the filters to only merchant on mobile because of limited space. On smaller devices, showing the extra filters will leave about 2 rows of the grid visible, which is not very nice looking or usable. Any thoughts on how to best fix that?

**Comment by marcushellberg** [comment]
IMO, the layout for horizontal mobile phone needs to be rethought, it doesn't work with either the desktop layout or the portrait mobile layout. Maybe have the filters on the side and grid full height? But then we would have 2 dark headers on top of each other. Thoughts?

**Comment by tuomasnironen** [comment]
A quick mockup to address the layout issue with mobile. Any good?
![iphone-6---overview---total---teal---2](https://cloud.githubusercontent.com/assets/13781525/11805017/3f9184d2-a311-11e5-8523-7b29b3089d6a.png)

**Comment by marcushellberg** [comment]
Fixed
