### ISSUE TITLE
Can't get past log-in page when ran locally. 

### ISSUE THREAD

**Issue by AdamVonHorn** [vaadin/expense-manager-demo#57]
I run the demo on my local machine and the red bar just goes across forever. The log-in page never fully pops up. How could I get rid of that log-in portion to go directly to the list view on the demo?

**Comment by marcushellberg** [comment]
What error are you getting? You can just hardcode the selected page in expense-app.html, but if the issue is with the db, that won't help you much.

**Comment by mygittyhubby** [comment]
got the same issue as Adam, only see the red bar going, no login, what am I missing?

**Comment by marcushellberg** [comment]
Please check the updated Polymer 2 version I just pushed. Let me know if you still have issues with that.

**Comment by mygittyhubby** [comment]
just tried the new Polymer 2 version, now the red bar is gone but no log-in either and the page is blank

![2017-07-05_111034](https://user-images.githubusercontent.com/3197158/27878295-9834803c-6172-11e7-840c-a94bc84975d4.png)

**Comment by mygittyhubby** [comment]
worked, thanks~

**Comment by mygittyhubby** [comment]
worked, thanks~
