### ISSUE TITLE
Make sure the app works as a PWA

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/expense-manager-demo#67]
Heads up: https://medium.com/@firt/pwas-are-coming-to-ios-11-3-cupertino-we-have-a-problem-2ff49fd7d6ea

**Comment by macjuan** [comment]
Related to that - I am running iOS 11.3 public beta 2 on iPhone 5S and with it, the offline detection does not work nor the prompt to add to home. Just saying...

**Comment by web-padawan** [comment]
LightHouse reports:

- old version:
[expensemanager.demo.vaadin.com_2018-02-28_13-01-43.html.zip](https://github.com/vaadin/expense-manager-demo/files/1767992/expensemanager.demo.vaadin.com_2018-02-28_13-01-43.html.zip)

- current version:
[expensemanager.demo.vaadin.com_2018-02-28_16-15-18.html.zip](https://github.com/vaadin/expense-manager-demo/files/1767993/expensemanager.demo.vaadin.com_2018-02-28_16-15-18.html.zip)

**Comment by web-padawan** [comment]
Tested as PWA on the following devices:

- Lenovo A5000 - Android 4.4
- Xiaomi Redmi Note 4 - Android 7.0

The following statements are verified:

- the "Add to home screen" invitation appears on the first load
- the app installation completes successfully
- the app can be loaded normally when going offline

**Comment by web-padawan** [comment]
@macjuan have you upgraded to the iOS 11.3 public beta 3? 
If so, the "Add to home screen" should work now. I don't have a device at my disposal to check.

**Comment by web-padawan** [comment]
I'm closing this now. Let's open a new ticket if we encounter any iOS-related PWA issues.
