### ISSUE TITLE
Replace filter inputs with combo boxes

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/expense-manager-demo#8]
I am guessing the inputs are not yet combo boxes because we don't have one available, yet. Anyhow, filtering the grid by having to type the values feels awkward (e.g. on the screenshot when you would want to limit the results with "Max ($): 200") and you start typing "2" the grid momentarily shows nothing because the value is so small). Also because there is a prefedined set of "Merchants" available, it would make more sense to have the options in a dropdown rather than having to type them yourself.

![screen shot 2015-12-11 at 11 04 05](https://cloud.githubusercontent.com/assets/13781525/11739901/75282c4e-9ff7-11e5-835b-64657d12d5e8.png)

**Comment by marcushellberg** [comment]
I agree that a combo box would work for the merchants, but I'm not sure I agree with making the min and max inputs dropdowns. Having every value from 5 to 50000 with increments of 5 is probably not any easier than just typing the number.

I could increase the debounce duration (duration between typing and the filtering) a bit if that would help slow typers avoid the empty flash

**Comment by tuomasnironen** [comment]
I see your point. Increasing debounce duration would make the app appear as slow so perhaps the safest bet would be no to change anything at this point. I would rather see a slider there when possible.

**Comment by marcushellberg** [comment]
Postponing this work until we figure out what's causing https://github.com/vaadin/vaadin-combo-box/issues/92
