### ISSUE TITLE
Broken image shown for default receipt

### ISSUE THREAD

**Issue by Artur-** [vaadin/expense-manager-demo#97]

**Comment by web-padawan** [comment]
The `rootPath` is intended to make it work: https://github.com/vaadin/expense-manager-demo/blob/master/src/expense-editor.html#L142

Both deployed free and pro versions are working, is it broken on latest master somehow?

**Comment by Artur-** [comment]
The img url is `//images/default-receipt.png` which translates to http://images/default-receipt.png.

**Comment by manolo** [comment]
Fixed in d827e7a27456cfab77d6924efe3a7f5829dd4b1e
